
package co.com.client.ws.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionPersonaServiceIface", targetNamespace = "http://iface.service.jee.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionPersonaServiceIface {


    /**
     * 
     * @return
     *     returns java.util.List<co.com.client.ws.servicio.PersonaVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPersonas", targetNamespace = "http://iface.service.jee.com.co/", className = "co.com.client.ws.servicio.ListarPersonas")
    @ResponseWrapper(localName = "listarPersonasResponse", targetNamespace = "http://iface.service.jee.com.co/", className = "co.com.client.ws.servicio.ListarPersonasResponse")
    public List<PersonaVO> listarPersonas();

}
