
package co.com.client.ws.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionUsuarioServiceImplService", targetNamespace = "http://impl.service.jee.com.co/", wsdlLocation = "http://localhost:8080/jee-ja/GestionUsuarioServiceImpl?wsdl")
public class GestionUsuarioServiceImplService
    extends Service
{

    private final static URL GESTIONUSUARIOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONUSUARIOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GESTIONUSUARIOSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.jee.com.co/", "GestionUsuarioServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jee-ja/GestionUsuarioServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONUSUARIOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GESTIONUSUARIOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GestionUsuarioServiceImplService() {
        super(__getWsdlLocation(), GESTIONUSUARIOSERVICEIMPLSERVICE_QNAME);
    }

    public GestionUsuarioServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONUSUARIOSERVICEIMPLSERVICE_QNAME, features);
    }

    public GestionUsuarioServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONUSUARIOSERVICEIMPLSERVICE_QNAME);
    }

    public GestionUsuarioServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONUSUARIOSERVICEIMPLSERVICE_QNAME, features);
    }

    public GestionUsuarioServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionUsuarioServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionUsuarioServiceIface
     */
    @WebEndpoint(name = "GestionUsuarioServiceImplPort")
    public GestionUsuarioServiceIface getGestionUsuarioServiceImplPort() {
        return super.getPort(new QName("http://impl.service.jee.com.co/", "GestionUsuarioServiceImplPort"), GestionUsuarioServiceIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionUsuarioServiceIface
     */
    @WebEndpoint(name = "GestionUsuarioServiceImplPort")
    public GestionUsuarioServiceIface getGestionUsuarioServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jee.com.co/", "GestionUsuarioServiceImplPort"), GestionUsuarioServiceIface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONUSUARIOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GESTIONUSUARIOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return GESTIONUSUARIOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
