
package co.com.client.ws.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionPersonaServiceImplService", targetNamespace = "http://impl.service.jee.com.co/", wsdlLocation = "http://localhost:8080/jee-ja/GestionPersonaServiceImpl?wsdl")
public class GestionPersonaServiceImplService
    extends Service
{

    private final static URL GESTIONPERSONASERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GESTIONPERSONASERVICEIMPLSERVICE_EXCEPTION;
    private final static QName GESTIONPERSONASERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.jee.com.co/", "GestionPersonaServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jee-ja/GestionPersonaServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONPERSONASERVICEIMPLSERVICE_WSDL_LOCATION = url;
        GESTIONPERSONASERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public GestionPersonaServiceImplService() {
        super(__getWsdlLocation(), GESTIONPERSONASERVICEIMPLSERVICE_QNAME);
    }

    public GestionPersonaServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONPERSONASERVICEIMPLSERVICE_QNAME, features);
    }

    public GestionPersonaServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONPERSONASERVICEIMPLSERVICE_QNAME);
    }

    public GestionPersonaServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONPERSONASERVICEIMPLSERVICE_QNAME, features);
    }

    public GestionPersonaServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionPersonaServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GestionPersonaServiceIface
     */
    @WebEndpoint(name = "GestionPersonaServiceImplPort")
    public GestionPersonaServiceIface getGestionPersonaServiceImplPort() {
        return super.getPort(new QName("http://impl.service.jee.com.co/", "GestionPersonaServiceImplPort"), GestionPersonaServiceIface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionPersonaServiceIface
     */
    @WebEndpoint(name = "GestionPersonaServiceImplPort")
    public GestionPersonaServiceIface getGestionPersonaServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.jee.com.co/", "GestionPersonaServiceImplPort"), GestionPersonaServiceIface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONPERSONASERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw GESTIONPERSONASERVICEIMPLSERVICE_EXCEPTION;
        }
        return GESTIONPERSONASERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
