
package co.com.client.ws.servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionUsuarioServiceIface", targetNamespace = "http://iface.service.jee.com.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionUsuarioServiceIface {


    /**
     * 
     * @return
     *     returns java.util.List<co.com.client.ws.servicio.UsuarioVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsuarios", targetNamespace = "http://iface.service.jee.com.co/", className = "co.com.client.ws.servicio.GetUsuarios")
    @ResponseWrapper(localName = "getUsuariosResponse", targetNamespace = "http://iface.service.jee.com.co/", className = "co.com.client.ws.servicio.GetUsuariosResponse")
    public List<UsuarioVO> getUsuarios();

}
